micronaut:
  application:
    name: SimpleCRUDgradle
  server:
    port: ${SERVER_PORT:8080}

datasource:
  default:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:defaultName}
    username: ${DB_USERNAME:defaultUsername}
    password: ${DB_PASSWORD:defaultPassword}
    db-type: postgres
    dialect: POSTGRES
    schema-generate: create-drop
    driver-class-name: org.postgresql.Driver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create